version: 2

sources:
  - name: dbt_ecommerce
    tables:
      - name: raw_billing_orders       
        external:
          location: "gs://dbt-ecommerce-raw/billing_orders/*.csv"
          options:
            format: "CSV"
            skip_leading_rows: 1
            field_delimiter: ","
        columns:
          - name: order_num
            data_type: int64
          - name: customer_cd
            data_type: int64
          - name: product_cd
            data_type: int64
          - name: unit_price
            data_type: numeric
          - name: quantity
            data_type: int64
          - name: discount
            data_type: numeric
          - name: total_amount
            data_type: numeric
          - name: created_at
            data_type: datetime
      - name: raw_customers
        external:
          location: "gs://dbt-ecommerce-raw/customers/*.csv"
          options:
            format: "CSV"
            skip_leading_rows: 1
            field_delimiter: ","
        columns:
          - name: customer_cd
            data_type: int64
          - name: surname
            data_type: string
          - name: name
            data_type: string
          - name: address
            data_type: string
          - name: city
            data_type: string
          - name: region
            data_type: string
          - name: country
            data_type: string
          - name: postal_code
            data_type: string
          - name: email
            data_type: string
          - name: updated_at
            data_type: datetime
      - name: raw_products
        external:
          location: "gs://dbt-ecommerce-raw/products/*.csv"
          options:
            format: "CSV"
            skip_leading_rows: 1
            field_delimiter: ","
        columns:
          - name: product_cd
            data_type: int64
          - name: name
            data_type: string
          - name: description
            data_type: string
          - name: category
            data_type: string
          - name: unit_price
            data_type: numeric
          - name: updated_at
            data_type: datetime